# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

variables:
  scheme: 'iOSHelloWorld'

steps:
- script: xcodebuild -version
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'test.p12'
    certPwd: 12345678()

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'HSBCRBWM.mobileprovision'

- task: Xcode@5
  inputs:
    scheme: '$(scheme)'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
